apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: example-pipeline-app-in-oc
    name: example-pipeline-app-in-oc
    namespace: example-pipeline-app-in-oc
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: example-pipeline-app-in-oc
      deploymentconfig: example-pipeline-app-in-oc
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    generation: 1
    labels:
      app: example-pipeline-app-in-oc
    name: example-pipeline-app-in-oc
    namespace: example-pipeline-app-in-oc
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: example-pipeline-app-in-oc
      deploymentconfig: example-pipeline-app-in-oc
    strategy:
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        name: example-pipeline-app-in-oc
        creationTimestamp: null
        labels:
          app: example-pipeline-app-in-oc
          deploymentconfig: example-pipeline-app-in-oc
      spec:
        containers:
        - env:
            - name: CONTAINER_MAX_MEMORY
              valueFrom:
                resourceFieldRef:
                  resource: limits.memory
          image: example-pipeline-app-in-oc:latest
          imagePullPolicy: Always
          name: example-pipeline-app-in-oc
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8443
            protocol: TCP
          - containerPort: 8778
            protocol: TCP
          resources:
            requests:
              memory: 768Mi
              cpu: 1
            limits:
              memory: 768Mi
              cpu: 1
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - example-pipeline-app-in-oc
        from:
          kind: ImageStreamTag
          name: example-pipeline-app-in-oc:latest
          namespace: example-pipeline-app-in-oc
      type: ImageChange
    - type: ConfigChange
  status:
    replicas: 0
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
      app: example-pipeline-app-in-oc
    name: example-pipeline-app-in-oc
    namespace: example-pipeline-app-in-oc
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: example-pipeline-app-in-oc:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        uri: https://github.com/francesco-losciale/example-pipeline-app-in-oc
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: java:11
          namespace: openshift
      type: Source
    successfulBuildsHistoryLimit: 5
  status:
    lastVersion: 1
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    generation: 1
    labels:
      app: example-pipeline-app-in-oc
    name: example-pipeline-app-in-oc
    namespace: example-pipeline-app-in-oc
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: image-registry.openshift-image-registry.svc:5000/example-pipeline-app-in-oc/example-pipeline-app-in-oc
    publicDockerImageRepository: default-route-openshift-image-registry.apps.us-east-2.starter.openshift-online.com/example-pipeline-app-in-oc/example-pipeline-app-in-oc
kind: List